# -*- coding: utf-8 -*-
"""Pyfortracc Tracking & Enhanced Forecasting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Zg2TvFqySwF7JtYfzzKDF4qGuQi89CN
"""

# CELL 1: Main Setup and Installation
# Run this cell first to set up the environment

# -*- coding: utf-8 -*-
"""
Google Colab Interactive NetCDF Tracking with PyForTraCC
CELL 1: Setup and Installation
"""

import os
import glob
import xarray as xr
import numpy as np
import pandas as pd
from datetime import datetime, timedelta
import warnings
import shutil
import zipfile
from pathlib import Path
warnings.filterwarnings('ignore')

# Google Colab specific imports
try:
    from google.colab import files
    from google.colab import widgets
    from IPython.display import display, HTML, clear_output
    import ipywidgets as w
    COLAB_ENV = True
    print("🚀 Running in Google Colab environment")
except ImportError:
    COLAB_ENV = False
    print("⚠️  Not running in Google Colab - some features may not work")

def install_packages():
    """Install required packages in Google Colab"""
    print("📦 Installing required packages...")
    print("This may take a few minutes...")

    packages = [
        "pyfortracc",
        "duckdb",
        "ipywidgets"
    ]

    for package in packages:
        print(f"Installing {package}...")
        result = os.system(f"pip install -q {package}")
        if result != 0:
            print(f"⚠️  Warning: {package} installation may have failed")

    try:
        import pyfortracc
        import duckdb
        print("✅ All packages installed successfully!")
        return True
    except ImportError as e:
        print(f"❌ Failed to import packages: {e}")
        return False

def inspect_netcdf_file(filepath):
    """Inspect NetCDF file structure with rich output"""
    print(f"\n🔍 Analyzing: {os.path.basename(filepath)}")

    try:
        ds = xr.open_dataset(filepath)

        # Display basic info
        print("📊 File Structure:")
        print(f"   Dimensions: {dict(ds.dims)}")
        print(f"   Coordinates: {list(ds.coords.keys())}")
        print(f"   Data Variables: {list(ds.data_vars.keys())}")

        # Find temperature variables
        temp_vars = []
        print("\n🌡️  Temperature Variable Candidates:")
        for var in ds.data_vars:
            var_lower = var.lower()
            attrs = str(ds[var].attrs).lower()
            if any(keyword in var_lower or keyword in attrs
                   for keyword in ['temp', 'bt', 'cmi', 'temperature', 'brightness']):
                temp_vars.append(var)
                print(f"   ✅ {var}: {ds[var].dims} {ds[var].shape}")
                if hasattr(ds[var], 'long_name'):
                    print(f"      Description: {ds[var].long_name}")

        if not temp_vars:
            print("   ⚠️  No obvious temperature variables found")
            print("   📋 All data variables:")
            for var in ds.data_vars:
                print(f"      - {var}: {ds[var].dims} {ds[var].shape}")
            temp_vars = list(ds.data_vars.keys())

        # Find coordinate variables
        lat_vars, lon_vars = [], []
        print("\n🌍 Coordinate Variable Candidates:")

        all_vars = list(ds.coords.keys()) + list(ds.data_vars.keys())
        for var in all_vars:
            var_lower = var.lower()
            attrs = str(ds[var].attrs).lower() if hasattr(ds[var], 'attrs') else ""

            if any(keyword in var_lower or keyword in attrs
                   for keyword in ['lat', 'latitude']) and var not in temp_vars:
                lat_vars.append(var)
                print(f"   🌍 Latitude: {var}")

            if any(keyword in var_lower or keyword in attrs
                   for keyword in ['lon', 'longitude']) and var not in temp_vars:
                lon_vars.append(var)
                print(f"   🌍 Longitude: {var}")

        # Show data sample
        if temp_vars:
            sample_data = ds[temp_vars[0]].values
            while len(sample_data.shape) > 2:
                sample_data = sample_data[0]
            print(f"\n📈 Sample data range: {np.nanmin(sample_data):.1f} to {np.nanmax(sample_data):.1f}")

        ds.close()

        return {
            'temp_vars': temp_vars,
            'lat_vars': lat_vars,
            'lon_vars': lon_vars,
            'all_vars': list(ds.data_vars.keys()),
            'coords': list(ds.coords.keys()),
            'dims': dict(ds.dims)
        }

    except Exception as e:
        print(f"❌ Error analyzing file: {e}")
        return None

# Run installation
print("🌟" * 30)
print("🌡️  NETCDF TRACKING WITH PYFORTRACC")
print("🌟" * 30)
print()
print("This notebook will help you track temperature/infrared features")
print("in your NetCDF files using the pyfortracc algorithm.")
print()

if install_packages():
    print("\n" + "="*50)
    print("✅ Setup complete! Run the next cell to upload your NetCDF files.")
    print("="*50)
else:
    print("\n❌ Setup failed. Please restart and try again.")

# CELL 2: Upload NetCDF Files
# Run this cell to upload your NetCDF files

def upload_netcdf_files():
    """Upload NetCDF files using Google Colab's file upload"""
    if not COLAB_ENV:
        print("❌ File upload only works in Google Colab")
        return None

    print("📁 Upload your NetCDF files")
    print("You can select multiple .nc files at once")
    print("Supported formats: .nc, .netcdf")
    print("\n⏳ Click 'Choose Files' below and select your NetCDF files...")

    # Create uploads directory
    upload_dir = "uploaded_files"
    if os.path.exists(upload_dir):
        shutil.rmtree(upload_dir)
    os.makedirs(upload_dir)

    # Upload files
    uploaded = files.upload()

    if not uploaded:
        print("❌ No files uploaded")
        return None

    # Move uploaded files to directory and filter NetCDF files
    netcdf_files = []
    for filename, content in uploaded.items():
        if filename.lower().endswith(('.nc', '.netcdf')):
            filepath = os.path.join(upload_dir, filename)
            with open(filepath, 'wb') as f:
                f.write(content)
            netcdf_files.append(filepath)
            print(f"✅ Uploaded: {filename}")
        else:
            print(f"⚠️  Skipped (not NetCDF): {filename}")

    if not netcdf_files:
        print("❌ No NetCDF files found in upload")
        return None

    print(f"\n🎉 Successfully uploaded {len(netcdf_files)} NetCDF files")
    return sorted(netcdf_files)

# Execute upload
print("📁 STEP 1: Upload NetCDF Files")
print("-" * 40)

netcdf_files = upload_netcdf_files()

if netcdf_files:
    # Store in global variable for next steps
    uploaded_files = netcdf_files

    # Inspect first file
    print(f"\n🔍 Analyzing first file: {os.path.basename(netcdf_files[0])}")
    file_info = inspect_netcdf_file(netcdf_files[0])

    if file_info:
        print("\n✅ File analysis complete!")
        print("📋 Summary:")
        print(f"   Temperature variables found: {len(file_info['temp_vars'])}")
        print(f"   Coordinate variables found: {len(file_info['lat_vars']) + len(file_info['lon_vars'])}")
        print(f"   Total data variables: {len(file_info['all_vars'])}")

        print("\n▶️  Ready for next step! Run the next cell to configure parameters.")
    else:
        print("❌ File analysis failed. Please check your NetCDF files.")
else:
    print("❌ Upload failed. Please try again.")

# CELL 3: Interactive Parameter Configuration
# Run this cell to configure tracking parameters using interactive widgets

def create_variable_selector(file_info):
    """Create interactive widgets for variable selection"""
    if not COLAB_ENV:
        return None

    print("🎛️  Interactive Variable Selection")

    # Temperature variable selector
    temp_options = file_info['temp_vars'] if file_info['temp_vars'] else file_info['all_vars']
    temp_dropdown = w.Dropdown(
        options=temp_options,
        value=temp_options[0],
        description='Temperature:',
        style={'description_width': 'initial'},
        layout=w.Layout(width='400px')
    )

    # Latitude variable selector
    lat_options = file_info['lat_vars'] if file_info['lat_vars'] else (file_info['coords'] + file_info['all_vars'])
    lat_dropdown = w.Dropdown(
        options=lat_options,
        value=lat_options[0] if lat_options else None,
        description='Latitude:',
        style={'description_width': 'initial'},
        layout=w.Layout(width='400px')
    )

    # Longitude variable selector
    lon_options = file_info['lon_vars'] if file_info['lon_vars'] else (file_info['coords'] + file_info['all_vars'])
    lon_dropdown = w.Dropdown(
        options=lon_options,
        value=lon_options[0] if lon_options else None,
        description='Longitude:',
        style={'description_width': 'initial'},
        layout=w.Layout(width='400px')
    )

    # Display widgets
    display(HTML("<h3>🎯 Select Variables:</h3>"))
    display(HTML("<p>Choose the variables from your NetCDF files:</p>"))
    display(temp_dropdown)
    display(lat_dropdown)
    display(lon_dropdown)

    return temp_dropdown, lat_dropdown, lon_dropdown

def create_parameter_widgets():
    """Create interactive widgets for tracking parameters"""
    if not COLAB_ENV:
        return None

    print("🎛️  Interactive Parameter Selection")

    # Thresholds
    warm_threshold = w.FloatSlider(
        value=235,
        min=180,
        max=300,
        step=5,
        description='Warm Threshold (K):',
        style={'description_width': 'initial'},
        layout=w.Layout(width='500px')
    )

    cold_threshold = w.FloatSlider(
        value=200,
        min=150,
        max=250,
        step=5,
        description='Cold Threshold (K):',
        style={'description_width': 'initial'},
        layout=w.Layout(width='500px')
    )

    # Cluster sizes
    warm_size = w.IntSlider(
        value=400,
        min=50,
        max=1000,
        step=50,
        description='Warm Min Size:',
        style={'description_width': 'initial'},
        layout=w.Layout(width='500px')
    )

    cold_size = w.IntSlider(
        value=100,
        min=25,
        max=500,
        step=25,
        description='Cold Min Size:',
        style={'description_width': 'initial'},
        layout=w.Layout(width='500px')
    )

    # Max files
    max_files = w.IntSlider(
        value=20,
        min=5,
        max=100,
        step=5,
        description='Max Files:',
        style={'description_width': 'initial'},
        layout=w.Layout(width='500px')
    )

    # Flip latitude
    flip_lat = w.Checkbox(
        value=True,
        description='Flip Latitude (recommended for satellite data)',
        style={'description_width': 'initial'}
    )

    # Display widgets
    display(HTML("<h3>⚙️ Tracking Parameters:</h3>"))
    display(HTML("<p><b>Temperature Thresholds:</b> Lower values = colder/higher clouds</p>"))
    display(warm_threshold)
    display(cold_threshold)
    display(HTML("<p><b>Minimum Cluster Sizes:</b> Number of pixels required to form a system</p>"))
    display(warm_size)
    display(cold_size)
    display(HTML("<p><b>Processing Options:</b></p>"))
    display(max_files)
    display(flip_lat)

    return warm_threshold, cold_threshold, warm_size, cold_size, max_files, flip_lat

# Execute configuration
print("🎛️  STEP 2: Configure Parameters")
print("-" * 40)

# Check if previous step completed
if 'file_info' not in globals():
    print("❌ Please upload files first! Run the previous cell.")
else:
    # Create variable selectors
    print("Creating variable selection widgets...")
    var_widgets = create_variable_selector(file_info)

    if var_widgets:
        print("\nCreating parameter widgets...")
        # Create parameter widgets
        param_widgets = create_parameter_widgets()

        if param_widgets:
            print("\n✅ Configuration complete!")
            print("\n📝 Instructions:")
            print("1. Use the dropdowns above to select your data variables")
            print("2. Adjust the sliders to set tracking parameters")
            print("3. Run the next cell to start tracking")
            print("\n💡 Tips:")
            print("• Lower temperature thresholds detect colder (higher) clouds")
            print("• Larger cluster sizes reduce noise but may miss small systems")
            print("• Start with fewer files for testing (5-10)")

            print("\n▶️  Ready for tracking! Run the next cell when configured.")
        else:
            print("❌ Failed to create parameter widgets")
    else:
        print("❌ Failed to create variable widgets")

# PRODUCTION-READY CELL 4: Balanced PyForTraCC for Accurate Results
# Optimized for reasonable speed while maintaining scientific accuracy

import re
from datetime import datetime, timedelta
import numpy as np

def extract_timestamp_from_filename(filename):
    """Extract timestamp from your specific filename format"""
    pattern = r'(\d{8})_(\d{4})\.nc'
    match = re.search(pattern, filename)

    if match:
        date_str = match.group(1)  # YYYYMMDD
        time_str = match.group(2)  # HHMM

        year = int(date_str[:4])
        month = int(date_str[4:6])
        day = int(date_str[6:8])
        hour = int(time_str[:2])
        minute = int(time_str[2:4])

        return datetime(year, month, day, hour, minute)
    else:
        raise ValueError(f"Cannot extract timestamp from filename: {filename}")

def smart_downsample_data(data, factor=2, method='block_mean'):
    """Smart downsampling that preserves important features"""
    if factor == 1:
        return data

    if method == 'block_mean':
        # Block averaging - preserves temperature gradients better
        h, w = data.shape
        new_h, new_w = h // factor, w // factor

        # Reshape and take mean of blocks
        reshaped = data[:new_h*factor, :new_w*factor].reshape(
            new_h, factor, new_w, factor
        )
        return np.nanmean(reshaped, axis=(1, 3))
    else:
        # Simple subsampling
        return data[::factor, ::factor]

def calculate_time_interval(netcdf_files):
    """Calculate the actual time interval between files"""
    if len(netcdf_files) < 2:
        return 30

    timestamps = []
    for file in netcdf_files[:3]:
        filename = os.path.basename(file)
        try:
            timestamp = extract_timestamp_from_filename(filename)
            timestamps.append(timestamp)
        except:
            continue

    if len(timestamps) >= 2:
        intervals = []
        for i in range(1, len(timestamps)):
            diff = (timestamps[i] - timestamps[i-1]).total_seconds() / 60
            intervals.append(int(diff))

        interval = max(set(intervals), key=intervals.count)
        print(f"   Detected time interval: {interval} minutes")
        return interval
    else:
        print("   Using default 30-minute interval")
        return 30

def prepare_input_files(netcdf_files, max_files=None):
    """Prepare NetCDF files for pyfortracc processing preserving original timestamps"""
    print("📋 Preparing files for tracking...")

    if os.path.exists('input/'):
        shutil.rmtree('input/')
    os.makedirs('input/')

    if max_files and max_files < len(netcdf_files):
        netcdf_files = netcdf_files[:max_files]
        print(f"   Limited to {max_files} files for processing")

    def get_timestamp(filepath):
        try:
            return extract_timestamp_from_filename(os.path.basename(filepath))
        except:
            return datetime.min

    netcdf_files = sorted(netcdf_files, key=get_timestamp)

    copied_files = []
    timestamps_used = []

    for src_file in netcdf_files:
        try:
            original_filename = os.path.basename(src_file)
            timestamp = extract_timestamp_from_filename(original_filename)
            timestamps_used.append(timestamp)

            dest_name = f"{timestamp.strftime('%Y%m%d%H%M')}.nc"
            dest_path = os.path.join('input', dest_name)

            shutil.copy2(src_file, dest_path)
            copied_files.append(dest_path)

            print(f"   {original_filename} → {dest_name}")

        except Exception as e:
            print(f"   ⚠️  Skipping {os.path.basename(src_file)}: {e}")
            continue

    if copied_files:
        print(f"✅ Prepared {len(copied_files)} files for processing")
        print(f"   Time period: {min(timestamps_used)} → {max(timestamps_used)}")

        sample_timestamp = timestamps_used[0].strftime('%Y%m%d%H%M')
        print(f"   Sample timestamp format: {sample_timestamp} (length: {len(sample_timestamp)})")

        return copied_files, calculate_time_interval(netcdf_files)
    else:
        print("❌ No files successfully prepared")
        return [], 30

# Global variables with production settings
GLOBAL_VARIABLE_NAME = None
GLOBAL_LAT_VAR = None
GLOBAL_LON_VAR = None
GLOBAL_FLIP_LAT = True
GLOBAL_PROCESSING_MODE = 'balanced'  # 'fast', 'balanced', 'accurate'

def production_read_function(filepath):
    """Production-ready read function with smart optimizations"""
    try:
        ds = xr.open_dataset(filepath)

        if GLOBAL_VARIABLE_NAME not in ds:
            raise ValueError(f"Variable '{GLOBAL_VARIABLE_NAME}' not found in {filepath}")

        data = ds[GLOBAL_VARIABLE_NAME].values

        # Handle multi-dimensional data
        while len(data.shape) > 2:
            data = data[0]

        if len(data.shape) != 2:
            raise ValueError(f"Data must be 2D, got shape: {data.shape}")

        original_shape = data.shape

        # Apply processing mode optimizations
        if GLOBAL_PROCESSING_MODE == 'fast':
            # Aggressive downsampling for testing
            data = smart_downsample_data(data, factor=3, method='block_mean')
        elif GLOBAL_PROCESSING_MODE == 'balanced':
            # Moderate downsampling - good balance of speed vs accuracy
            if original_shape[0] > 3000 or original_shape[1] > 3000:
                data = smart_downsample_data(data, factor=2, method='block_mean')
                print(f"   Downsampled {original_shape} → {data.shape} for efficiency")
        # 'accurate' mode: no downsampling

        # Flip latitude if specified
        if GLOBAL_FLIP_LAT:
            data = data[::-1]

        # Check for valid data
        if np.isnan(data).all():
            raise ValueError("All data values are NaN")

        ds.close()
        return data.astype(np.float32)

    except Exception as e:
        print(f"❌ Error reading {os.path.basename(filepath)}: {e}")
        raise

def get_spatial_info(filepath, lat_var, lon_var):
    """Extract spatial domain information"""
    try:
        ds = xr.open_dataset(filepath)

        lats = ds[lat_var].values
        lons = ds[lon_var].values

        lat_min, lat_max = float(np.nanmin(lats)), float(np.nanmax(lats))
        lon_min, lon_max = float(np.nanmin(lons)), float(np.nanmax(lons))

        print(f"🗺️  Spatial Domain: lon({lon_min:.2f}, {lon_max:.2f}), lat({lat_min:.2f}, {lat_max:.2f})")

        ds.close()
        return lon_min, lon_max, lat_min, lat_max

    except Exception as e:
        print(f"⚠️  Error extracting spatial info: {e}")
        return -180, 180, -90, 90

def create_production_namelist_config(lon_min, lon_max, lat_min, lat_max,
                                    thresholds, min_cluster_size, delta_time, mode='balanced'):
    """Create production-ready pyfortracc configuration"""

    if mode == 'fast':
        # Fast mode - for testing only
        config = {
            'spl_correction': False,
            'mrg_correction': True,   # Keep merge - important for tracking
            'inc_correction': False,
            'opt_correction': True,   # Keep for better tracking
            'elp_correction': False,
            'validation': False
        }
        print("⚡ Using FAST mode - for testing only!")

    elif mode == 'balanced':
        # Balanced mode - good accuracy with reasonable speed
        config = {
            'spl_correction': True,   # Keep - important for system splitting
            'mrg_correction': True,   # Keep - important for system merging
            'inc_correction': False,  # Skip - less critical
            'opt_correction': True,   # Keep - improves tracking accuracy
            'elp_correction': False,  # Skip - computationally expensive
            'validation': True        # Keep - ensures result quality
        }
        print("⚖️  Using BALANCED mode - production ready!")

    else:  # accurate
        # Accurate mode - all corrections enabled
        config = {
            'spl_correction': True,
            'mrg_correction': True,
            'inc_correction': True,
            'opt_correction': True,
            'elp_correction': True,
            'validation': True
        }
        print("🎯 Using ACCURATE mode - maximum quality!")

    # Base configuration
    base_config = {
        'input_path': 'input/',
        'output_path': 'output/',
        'thresholds': thresholds,
        'min_cluster_size': min_cluster_size,
        'operator': '<=',
        'timestamp_pattern': '%Y%m%d%H%M',
        'pattern_position': [0, 12],
        'delta_time': delta_time,
        'lon_min': lon_min,
        'lon_max': lon_max,
        'lat_min': lat_min,
        'lat_max': lat_max,
    }

    # Merge configurations
    base_config.update(config)
    return base_config

def run_production_tracking_workflow():
    """Run production-ready tracking workflow"""
    global GLOBAL_VARIABLE_NAME, GLOBAL_LAT_VAR, GLOBAL_LON_VAR, GLOBAL_FLIP_LAT, GLOBAL_PROCESSING_MODE

    print("🏭 Starting PRODUCTION PyForTraCC workflow...")

    # Check prerequisites
    if 'uploaded_files' not in globals():
        print("❌ No uploaded files found! Please run the upload cell first.")
        return None, None, False

    if 'var_widgets' not in globals() or 'param_widgets' not in globals():
        print("❌ Configuration not found! Please run the configuration cell first.")
        return None, None, False

    # Get widget values
    GLOBAL_VARIABLE_NAME = var_widgets[0].value
    GLOBAL_LAT_VAR = var_widgets[1].value
    GLOBAL_LON_VAR = var_widgets[2].value

    warm_thresh = param_widgets[0].value
    cold_thresh = param_widgets[1].value
    warm_size = param_widgets[2].value
    cold_size = param_widgets[3].value
    max_files = param_widgets[4].value
    GLOBAL_FLIP_LAT = param_widgets[5].value

    # PROCESSING MODE SELECTION
    print("\n🎛️  PROCESSING MODE SELECTION:")
    print("=" * 50)

    num_files = min(len(uploaded_files), max_files)

    if num_files <= 3:
        GLOBAL_PROCESSING_MODE = 'balanced'
        print("✅ Auto-selected BALANCED mode (≤3 files)")
    elif num_files <= 6:
        GLOBAL_PROCESSING_MODE = 'balanced'
        print("✅ Auto-selected BALANCED mode (≤6 files)")
    else:
        # For many files, offer choice
        print("📊 You have many files. Choose processing mode:")
        print("   BALANCED: Good accuracy, reasonable speed (RECOMMENDED)")
        GLOBAL_PROCESSING_MODE = 'balanced'

    # Expected timing based on mode and file count
    if GLOBAL_PROCESSING_MODE == 'fast':
        expected_time = f"{num_files * 0.5:.1f}-{num_files * 2:.1f} minutes"
    elif GLOBAL_PROCESSING_MODE == 'balanced':
        expected_time = f"{num_files * 2:.1f}-{num_files * 8:.1f} minutes"
    else:
        expected_time = f"{num_files * 5:.1f}-{num_files * 20:.1f} minutes"

    print(f"\n🎯 Production Configuration Summary:")
    print("=" * 50)
    print(f"   📊 Files to process: {num_files}")
    print(f"   🌡️  Temperature variable: {GLOBAL_VARIABLE_NAME}")
    print(f"   🌍 Coordinates: {GLOBAL_LAT_VAR}, {GLOBAL_LON_VAR}")
    print(f"   🎚️  Thresholds: {warm_thresh}K (warm), {cold_thresh}K (cold)")
    print(f"   📏 Min cluster sizes: {warm_size}, {cold_size} pixels")
    print(f"   🔄 Flip latitude: {GLOBAL_FLIP_LAT}")
    print(f"   ⚙️  Mode: {GLOBAL_PROCESSING_MODE.upper()}")
    print(f"   ⏱️  Expected time: {expected_time}")

    try:
        # Prepare files
        prepared_files, delta_time = prepare_input_files(uploaded_files, max_files)

        if not prepared_files:
            print("❌ No files prepared successfully")
            return None, None, False

        # Test reading
        print("\n🧪 Testing production data reading...")
        test_data = production_read_function(prepared_files[0])
        print(f"✅ Data shape: {test_data.shape}")
        print(f"   Data range: {test_data.min():.1f} to {test_data.max():.1f} K")
        print(f"   Valid pixels: {(~np.isnan(test_data)).sum():,}")

        # Data quality check
        valid_ratio = (~np.isnan(test_data)).sum() / test_data.size
        if valid_ratio < 0.1:
            print("⚠️  Warning: Low data coverage, results may be unreliable")
        elif valid_ratio > 0.8:
            print("✅ Good data coverage detected")

        # Get spatial info
        lon_min, lon_max, lat_min, lat_max = get_spatial_info(prepared_files[0], GLOBAL_LAT_VAR, GLOBAL_LON_VAR)

        # Create production configuration
        name_list = create_production_namelist_config(
            lon_min, lon_max, lat_min, lat_max,
            [warm_thresh, cold_thresh],
            [warm_size, cold_size],
            delta_time,
            GLOBAL_PROCESSING_MODE
        )

        print(f"\n🔧 ALGORITHM SETTINGS:")
        print("=" * 30)
        enabled_corrections = [k for k, v in name_list.items() if k.endswith('_correction') and v]
        print(f"   ✅ Enabled: {', '.join(enabled_corrections)}")
        print(f"   🔍 Validation: {'✅ ON' if name_list['validation'] else '❌ OFF'}")
        print(f"   ⏰ Time interval: {delta_time} minutes")

        # Final confirmation for production run
        print(f"\n🚀 Starting production tracking...")
        print(f"⏳ Expected duration: {expected_time}")
        print("   Progress will be shown below...")

        from pyfortracc import track
        track(name_list, production_read_function)

        print("✅ Production tracking completed successfully!")

        # Quality assessment
        print(f"\n📊 QUALITY ASSESSMENT:")
        print("=" * 30)

        # Check if results exist
        result_files = glob.glob('output/track/trackingtable/*.parquet')
        if result_files:
            print(f"✅ Results generated: {len(result_files)} files")

            # Quick quality check
            try:
                import duckdb
                con = duckdb.connect(':memory:')
                df = con.execute("SELECT COUNT(*) as records, COUNT(DISTINCT uid) as systems FROM parquet_scan('output/track/trackingtable/*.parquet')").fetch_df()

                records = df['records'].iloc[0]
                systems = df['systems'].iloc[0]

                print(f"✅ Tracking records: {records:,}")
                print(f"✅ Unique systems: {systems:,}")

                if records > 0 and systems > 0:
                    avg_lifetime = records / systems
                    print(f"✅ Average system lifetime: {avg_lifetime:.1f} time steps")

                    if avg_lifetime > 1.5:
                        print("🎯 GOOD QUALITY: Systems are being tracked across time steps")
                    else:
                        print("⚠️  SHORT LIFETIMES: Consider adjusting thresholds")

                else:
                    print("⚠️  NO SYSTEMS DETECTED: Try lowering thresholds")

            except Exception as e:
                print(f"⚠️  Could not assess quality: {e}")
        else:
            print("❌ No result files found")

        # Store globally
        globals()['name_list'] = name_list
        globals()['read_function'] = production_read_function

        return name_list, production_read_function, True

    except Exception as e:
        print(f"❌ Production tracking failed: {e}")
        print("\n🔧 TROUBLESHOOTING:")
        print("=" * 20)
        print("• If too slow: Try 'fast' mode first")
        print("• If no systems detected: Lower temperature thresholds")
        print("• If too many systems: Raise minimum cluster sizes")
        print("• If memory issues: Process fewer files")
        import traceback
        traceback.print_exc()
        return None, None, False

# Execute production tracking
print("🏭 STEP 3: Production-Ready Tracking")
print("=" * 60)

name_list_result, read_function_result, success = run_production_tracking_workflow()

if success:
    print("\n" + "🏆" * 25)
    print("🎉 PRODUCTION TRACKING COMPLETE! 🎉")
    print("🏆" * 25)
    print("\n📊 Quality-assured results saved to 'output/' directory")
    print("▶️  Run the next cell to analyze your results!")
else:
    print("\n❌ Production tracking failed. Check troubleshooting tips above.")

# PRODUCTION GUIDELINES
print("\n📋 PRODUCTION USAGE GUIDELINES:")
print("=" * 50)
print("✅ BALANCED mode: Recommended for operational use")
print("✅ Keeps essential corrections (split, merge, optimization)")
print("✅ Includes validation for result quality assurance")
print("✅ Smart downsampling only for very large datasets")
print("✅ Preserves original timestamps and intervals")
print("✅ Automatic quality assessment")
print("\n⏱️  TYPICAL PROCESSING TIMES:")
print("   • 3 files: 3-10 minutes")
print("   • 5 files: 8-25 minutes")
print("   • 10 files: 20-60 minutes")
print("   • 20+ files: 1-3 hours")
print("\n🎯 Results should be suitable for scientific analysis!")

# Import duckdb
import duckdb

# Connect to the database
con = duckdb.connect(database=':memory:', read_only=False)

# Open tracking table
tracking_table = con.execute(f"""SELECT *
                             FROM parquet_scan('output/track/trackingtable/*.parquet',
                             union_by_name=True)
                             """).fetch_df()

from pyfortracc import plot_animation
import numpy as np
import os

plot_animation(
    read_function=read_function,
    name_list=name_list,
    start_timestamp= str(tracking_table['timestamp'].min()), # Start timestamp
    end_timestamp= str(tracking_table['timestamp'].max()), # End timestamp

    figsize=(8, 6),
)

# Visualize as animation.
plot_animation(read_function=read_function, # Read function
                          figsize=(6,5), # Figure size
                          name_list=name_list, # Name list dictionary
                          start_timestamp = str(tracking_table['timestamp'].min()), # Start timestamp
                          end_timestamp= str(tracking_table['timestamp'].max()), # End timestamp
                          info_col_name=False, # Info column name
                          cbar_title='Temperature(k)', # Colorbar title
                          trajectory=True, # Plot the trajectory
                          smooth_trajectory=True, # Smooth the trajectory
                          cmap='turbo', # Colormap
                          min_val=160, # Min value
                          max_val=235, # Max value
                          nan_value=235, # NaN value
                          nan_operation=np.greater_equal, # NaN operator
                          bound_color='blue', # Bound color
                          info_cols=['uid'], # Info columns from tracking table
                          parallel=False
                          )

# CELL 5: Results Analysis (ANALYSIS ONLY)

def analyze_results():
    """Analyze and display tracking results with proper column detection"""
    try:
        print("📊 Analyzing tracking results...")

        result_files = glob.glob('output/track/trackingtable/*.parquet')
        if not result_files:
            print("❌ No results found in output directory")
            print("   Make sure the tracking step completed successfully")
            return None

        print(f"📁 Found {len(result_files)} result files")

        # Load results using duckdb
        import duckdb
        con = duckdb.connect(':memory:')

        tracking_table = con.execute("""
            SELECT * FROM parquet_scan('output/track/trackingtable/*.parquet',
            union_by_name=True)
        """).fetch_df()

        # Display comprehensive statistics
        print(f"\n📈 TRACKING RESULTS SUMMARY")
        print("=" * 40)
        print(f"📋 Total tracking records: {len(tracking_table):,}")
        print(f"🎯 Unique systems detected: {tracking_table['uid'].nunique()}")

        # Debug: Show actual column names
        print(f"\n🔍 ACTUAL COLUMNS IN TRACKING TABLE:")
        print("=" * 40)
        for i, col in enumerate(tracking_table.columns):
            print(f"   {i+1:2d}. {col} ({tracking_table[col].dtype})")

        # Check for timestamp column variations
        time_cols = [col for col in tracking_table.columns if 'time' in col.lower() or 'date' in col.lower()]
        if time_cols:
            time_col = time_cols[0]
            print(f"⏰ Using time column: {time_col}")
            print(f"⏰ Time steps analyzed: {tracking_table[time_col].nunique()}")
            print(f"📅 Time period: {tracking_table[time_col].min()} → {tracking_table[time_col].max()}")
        else:
            print("⚠️  No time column found")

        # System lifetime analysis
        lifetimes = tracking_table.groupby('uid').size()
        print(f"\n🕒 SYSTEM LIFETIME STATISTICS")
        print("=" * 40)
        print(f"📊 Average lifetime: {lifetimes.mean():.1f} time steps")
        print(f"📊 Median lifetime: {lifetimes.median():.1f} time steps")
        print(f"🏆 Longest system: {lifetimes.max()} time steps")
        print(f"⚡ Short systems (≤2 steps): {(lifetimes <= 2).sum()}")
        print(f"🌀 Long systems (>5 steps): {(lifetimes > 5).sum()}")
        print(f"🌪️  Very long systems (>10 steps): {(lifetimes > 10).sum()}")

        # Look for temperature/intensity columns (multiple possible names)
        temp_cols = [col for col in tracking_table.columns
                    if any(keyword in col.lower() for keyword in ['temp', 'bt', 'intensity', 'mean', 'min', 'max', 'value'])]

        if temp_cols:
            temp_col = temp_cols[0]  # Use first match
            print(f"\n🌡️  TEMPERATURE/INTENSITY STATISTICS")
            print("=" * 40)
            print(f"📊 Using column: {temp_col}")
            print(f"🧊 Minimum value: {tracking_table[temp_col].min():.1f}")
            print(f"🌡️  Maximum value: {tracking_table[temp_col].max():.1f}")
            print(f"📊 Average value: {tracking_table[temp_col].mean():.1f}")
        else:
            temp_col = None
            print(f"\n⚠️  No temperature/intensity columns found")

        # Look for size/area columns
        size_cols = [col for col in tracking_table.columns
                    if any(keyword in col.lower() for keyword in ['area', 'size', 'pixels', 'count'])]

        if size_cols:
            size_col = size_cols[0]  # Use first match
            print(f"\n📏 SIZE STATISTICS")
            print("=" * 40)
            print(f"📊 Using column: {size_col}")
            print(f"🔍 Smallest system: {tracking_table[size_col].min():.0f}")
            print(f"🌀 Largest system: {tracking_table[size_col].max():.0f}")
            print(f"📊 Average size: {tracking_table[size_col].mean():.0f}")
        else:
            size_col = None
            print(f"\n⚠️  No size/area columns found")

        # Display sample data
        print(f"\n📋 SAMPLE TRACKING DATA")
        print("=" * 40)
        print("\nFirst 10 records:")
        display(tracking_table.head(10))

        # System summary
        print(f"\n🎯 TOP 10 LONGEST-LIVED SYSTEMS")
        print("=" * 40)
        top_systems = lifetimes.sort_values(ascending=False).head(10)
        for uid, lifetime in top_systems.items():
            system_data = tracking_table[tracking_table['uid'] == uid]
            if time_cols:
                start_time = system_data[time_col].min()
                end_time = system_data[time_col].max()
                extra_info = f" ({start_time} → {end_time})"
            else:
                extra_info = ""

            if temp_col:
                min_temp = system_data[temp_col].min()
                print(f"   System {uid}: {lifetime} steps{extra_info}, min value: {min_temp:.1f}")
            else:
                print(f"   System {uid}: {lifetime} steps{extra_info}")

        return tracking_table, temp_col, size_col, time_col if time_cols else None

    except Exception as e:
        print(f"❌ Error analyzing results: {e}")
        import traceback
        traceback.print_exc()
        return None, None, None, None

# MAIN EXECUTION — Analysis Only
print("📊 STEP 4: Results Analysis")
print("=" * 60)

print("\n1️⃣ Analyzing tracking results...")
tracking_results, temp_col, size_col, time_col = analyze_results()

if tracking_results is not None:
    print(f"\n✅ Analysis complete! Found {len(tracking_results)} tracking records")
else:
    print("\n❌ Analysis failed. Please check that tracking completed successfully.")

# ============================================================
#  PHYSICS-AWARE WIDE & DEEP FORECAST – FIXED VERSION
# ============================================================
# Installs ----------------------------------------------------
!pip -q install lightgbm torch_optimizer

# Imports -----------------------------------------------------
import os, glob, warnings, random, math, joblib
import numpy as np, pandas as pd
warnings.filterwarnings("ignore")
import torch, torch.nn as nn
from torch.utils.data import Dataset, DataLoader, WeightedRandomSampler
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error

# 1 ────────────────────────────────────────────────────────────
#   LOAD TRACKED DATA
# ----------------------------------------------------------------
PAR_DIR = "output/track/trackingtable/"
files   = glob.glob(os.path.join(PAR_DIR,"*.parquet"))
if not files: raise RuntimeError(f"No parquet files in {PAR_DIR}")
df = pd.concat([pd.read_parquet(f) for f in files], ignore_index=True)
df = df.sort_values(["uid","timestamp"]).reset_index(drop=True)
print(f"📂 {len(df)} rows from {len(files)} parquet files")

# 2 ────────────────────────────────────────────────────────────
#   FEATURE ENGINEERING  (Seven-point plan #1)
# ----------------------------------------------------------------
BASE = ["size","mean","lifetime","min","max","std"]
for col in BASE:
    if col not in df: raise RuntimeError(f"Missing column {col}")

# physics ranges & anomalies
BT_MEDIAN        = df["mean"].median()
df["bt_anom"]    = df["mean"] - BT_MEDIAN
df["bt_range"]   = df["max"] - df["min"]
df["size_norm"]  = df["size"] / df.groupby("uid")["size"].transform("max").clip(lower=1)
df["opt_proxy"]  = df["std"]  / (df["bt_range"] + 1e-4)
df["rank_scene"] = df.groupby("file")["mean"].rank(pct=True)

# drop impossible temps
df = df[(df["mean"]>=150)&(df["mean"]<=350)]
TARGET = "bt_anom"

# keep numeric features only
FEATS = ["size_norm","lifetime","bt_range","opt_proxy","rank_scene","min","max"]
if "expansion" in df and df["expansion"].notna().mean()>0.2:
    df["expansion"].fillna(0,inplace=True)
    FEATS.append("expansion")
if {"u_","v_"}.issubset(df.columns) and df[["u_","v_"]].notna().all(axis=1).mean()>0.2:
    FEATS.extend(["u_","v_"])

print(f"🧩 Feature set: {FEATS}")

# 3 ────────────────────────────────────────────────────────────
#   MODE SELECTION  (Snapshot vs Sequence)
# ----------------------------------------------------------------
MAX_LAG        = 4
seq_capable    = (df.groupby("uid").size() >= (MAX_LAG+1)).sum()
SEQ_MODE       = seq_capable >= 30
print("🔧 Mode :", "SEQUENCE" if SEQ_MODE else "SNAPSHOT")

# 4 ────────────────────────────────────────────────────────────
#   TRAIN / VAL / TEST SPLIT
# ----------------------------------------------------------------
rng = np.random.default_rng(7)
if SEQ_MODE:
    uids = df["uid"].unique(); rng.shuffle(uids)
    n    = len(uids)
    train_uid, val_uid, test_uid = np.split(uids,[int(.7*n), int(.85*n)])
    dtrain, dval, dtest = (df[df["uid"].isin(u)] for u in (train_uid,val_uid,test_uid))
else:
    idx = np.arange(len(df)); rng.shuffle(idx)
    n = len(idx)
    itrain, ival, itest = np.split(idx,[int(.7*n), int(.85*n)])
    dtrain, dval, dtest = (df.iloc[i] for i in (itrain,ival,itest))

# 5 ────────────────────────────────────────────────────────────
#   SCALING & TREE (Wide part) - FIXED LGBM
# ----------------------------------------------------------------
import lightgbm as lgb

wide_scaler = StandardScaler().fit(dtrain[FEATS])
X_train_scaled = wide_scaler.transform(dtrain[FEATS])
X_val_scaled = wide_scaler.transform(dval[FEATS])
X_test_scaled = wide_scaler.transform(dtest[FEATS])

# Create datasets
train_data = lgb.Dataset(X_train_scaled, label=dtrain[TARGET])
val_data = lgb.Dataset(X_val_scaled, label=dval[TARGET], reference=train_data)

# Fixed parameters
params = {
    'objective': 'regression',
    'metric': 'rmse',
    'boosting_type': 'gbdt',
    'num_leaves': 31,
    'learning_rate': 0.03,
    'feature_fraction': 0.8,
    'bagging_fraction': 0.9,
    'bagging_freq': 5,
    'min_data_in_leaf': 5,
    'lambda_l1': 0.2,
    'lambda_l2': 1.0,
    'verbose': -1
}

# Train with early stopping
lgb_model = lgb.train(
    params,
    train_data,
    valid_sets=[train_data, val_data],
    num_boost_round=1000,
    callbacks=[lgb.early_stopping(100), lgb.log_evaluation(0)]
)

# Make predictions for all sets
dtrain = dtrain.copy()
dval = dval.copy()
dtest = dtest.copy()

dtrain["gbt_pred"] = lgb_model.predict(X_train_scaled)
dval["gbt_pred"] = lgb_model.predict(X_val_scaled)
dtest["gbt_pred"] = lgb_model.predict(X_test_scaled)

FEATS_WIDEDEEP = FEATS + ["gbt_pred"]

# save scalers / booster
joblib.dump(wide_scaler,"wide_scaler.pkl")
lgb_model.save_model("wide_booster.txt")

# 6 ────────────────────────────────────────────────────────────
#   DATASETS & SAMPLERS
# ----------------------------------------------------------------
class SnapDS(Dataset):
    def __init__(self, frame):
        self.x = torch.tensor(frame[FEATS_WIDEDEEP].values, dtype=torch.float32)
        self.y = torch.tensor(frame[TARGET].values,          dtype=torch.float32)
    def __len__(self): return len(self.y)
    def __getitem__(self,i): return self.x[i], self.y[i]

class SeqDS(Dataset):
    def __init__(self, frame, lag):
        seq,y=[] ,[]
        for uid,g in frame.groupby("uid"):
            if len(g)<=lag: continue
            a = g[FEATS_WIDEDEEP].values.astype("float32")
            t = g[TARGET].values.astype("float32")
            for i in range(lag,len(g)):
                seq.append(a[i-lag:i]); y.append(t[i])
        if not seq: raise RuntimeError("No sequences - reduce lag")
        self.x = torch.tensor(np.stack(seq))
        self.y = torch.tensor(np.array(y))
    def __len__(self): return len(self.y)
    def __getitem__(self,i): return self.x[i], self.y[i]

if SEQ_MODE:
    train_ds = SeqDS(dtrain,MAX_LAG); val_ds=SeqDS(dval,MAX_LAG); test_ds=SeqDS(dtest,MAX_LAG)
    # oversample multi-step sequences (rare)
    weights = torch.ones(len(train_ds))
    sampler = WeightedRandomSampler(weights, num_samples=len(weights)*3, replacement=True)
    train_loader = DataLoader(train_ds,batch_size=64,sampler=sampler)
else:
    train_ds,val_ds,test_ds = (SnapDS(x) for x in (dtrain,dval,dtest))
    train_loader = DataLoader(train_ds,batch_size=32,shuffle=True)

val_loader  = DataLoader(val_ds ,batch_size=64)
test_loader = DataLoader(test_ds,batch_size=64)
print(f"📦 Data – Train {len(train_ds)}, Val {len(val_ds)}, Test {len(test_ds)}")

# 7 ────────────────────────────────────────────────────────────
#   DEEP PART + HEAD  (Seven-point plan #3 & #5)
# ----------------------------------------------------------------
INP  = train_ds[0][0].shape[-1] if SEQ_MODE else len(FEATS_WIDEDEEP)
HID  = 128

class FFDeep(nn.Module):
    def __init__(self, inp=INP):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(inp,HID), nn.ReLU(), nn.Dropout(0.25),
            nn.Linear(HID,64), nn.ReLU(), nn.Dropout(0.25),
            nn.Linear(64,1))
    def forward(self,x): return self.net(x).squeeze(-1)

class LSTMDeep(nn.Module):
    def __init__(self, inp, lag):
        super().__init__()
        self.fc = nn.Linear(inp, HID)
        self.lstm = nn.LSTM(HID,HID,2,batch_first=True,dropout=0.25)
        self.head = nn.Sequential(nn.Linear(HID,64),nn.ReLU(),nn.Dropout(0.25),nn.Linear(64,1))
    def forward(self,x):
        x = self.fc(x)
        o,_ = self.lstm(x)
        return self.head(o[:,-1]).squeeze(-1)

device = "cuda" if torch.cuda.is_available() else "cpu"
deep = (LSTMDeep(INP,MAX_LAG) if SEQ_MODE else FFDeep(INP)).to(device)

# Simple optimizer (avoiding lookahead for compatibility)
opt = torch.optim.AdamW(deep.parameters(), lr=3e-4, weight_decay=1e-4)
sched = torch.optim.lr_scheduler.ReduceLROnPlateau(opt,patience=75,factor=0.3,verbose=True)

def phys_loss(pred,tgt,x,lam=0.08):
    mse   = nn.MSELoss()(pred,tgt)
    bound = torch.mean(torch.relu(pred+BT_MEDIAN-350)+torch.relu(150-(pred+BT_MEDIAN)))
    if len(pred) > 1 and "size_norm" in FEATS_WIDEDEEP:
        energy= x[:,FEATS_WIDEDEEP.index("size_norm")] * (pred+BT_MEDIAN)
        econ  = torch.mean((energy[1:]-energy[:-1])**2)
    else:
        econ = torch.tensor(0.0, device=pred.device)
    return mse + lam*(bound + 0.3*econ)

# 8 ────────────────────────────────────────────────────────────
#   TRAINING LOOP  (Seven-point plan #5)
# ----------------------------------------------------------------
EPOCHS   = 1500
best_val = math.inf
wait     = 0

print("🚀 Training ...")
for epoch in range(1,EPOCHS+1):
    deep.train(); tl=0
    for xb,yb in train_loader:
        xb,yb = xb.to(device), yb.to(device)
        opt.zero_grad()
        pred = deep(xb)
        loss = phys_loss(pred,yb,xb)
        loss.backward()
        nn.utils.clip_grad_norm_(deep.parameters(),0.5)
        opt.step(); tl+=loss.item()*len(xb)
    tl/=len(train_ds)

    # validation
    deep.eval(); vl=0
    with torch.no_grad():
        for xb,yb in val_loader:
            xb,yb = xb.to(device), yb.to(device)
            vl+=phys_loss(deep(xb), yb, xb).item()*len(xb)
    vl/=len(val_ds)
    sched.step(vl)

    if epoch%50==0 or vl<best_val:
        print(f"Epoch {epoch:04d}  Train {tl:.4f}  Val {vl:.4f}")
    if vl<best_val:
        best_val=vl; wait=0
        torch.save(deep.state_dict(),"deep_best.pt")
    else:
        wait+=1
        if wait>=150: print("⏹️  Early stop"); break

deep.load_state_dict(torch.load("deep_best.pt"))

# 9 ────────────────────────────────────────────────────────────
#   EVALUATION  (Seven-point plan #6)
# ----------------------------------------------------------------
deep.eval(); preds,gts=[],[]
with torch.no_grad():
    for xb,yb in test_loader:
        xb,yb = xb.to(device), yb.to(device)
        preds.extend(deep(xb).cpu().numpy())
        gts.extend(yb.cpu().numpy())

preds = np.array(preds)+BT_MEDIAN   # de-normalise
gts   = np.array(gts)   +BT_MEDIAN

mse  = mean_squared_error(gts,preds)
rmse = np.sqrt(mse)
mae  = mean_absolute_error(gts,preds)
r2   = 1 - mse/np.var(gts)

# Physical bounds check
violations = np.sum((preds < 150) | (preds > 350))
violation_rate = violations / len(preds) * 100

print("\n📈 PRODUCTION METRICS")
print(f"  RMSE: {rmse:.2f} K")
print(f"  MAE:  {mae:.2f} K")
print(f"  R²:   {r2:.3f}")
print(f"  Physical bound violations: {violations}/{len(preds)} ({violation_rate:.1f}%)")

# Save results
results_df = pd.DataFrame({
    "truth": gts,
    "pred": preds,
    "residual": preds - gts,
    "abs_error": np.abs(preds - gts)
})
results_df.to_csv("production_physics_forecast.csv", index=False)

print("✅ Saved production_physics_forecast.csv")

# Basic visualization
import matplotlib.pyplot as plt
plt.figure(figsize=(12, 4))

plt.subplot(1, 3, 1)
plt.plot(gts[:100], label='True', alpha=0.8)
plt.plot(preds[:100], label='Predicted', alpha=0.8, linestyle='--')
plt.title('Temperature Forecast')
plt.ylabel('Temperature [K]')
plt.legend()
plt.grid(True)

plt.subplot(1, 3, 2)
plt.scatter(gts, preds, alpha=0.6)
plt.plot([gts.min(), gts.max()], [gts.min(), gts.max()], 'r--')
plt.xlabel('True Temperature [K]')
plt.ylabel('Predicted Temperature [K]')
plt.title(f'Accuracy (R²={r2:.3f})')
plt.grid(True)

plt.subplot(1, 3, 3)
residuals = preds - gts
plt.hist(residuals, bins=20, alpha=0.7, edgecolor='black')
plt.xlabel('Residuals [K]')
plt.ylabel('Frequency')
plt.title(f'Error Distribution (σ={np.std(residuals):.1f}K)')
plt.grid(True)

plt.tight_layout()
plt.show()

print("This is genuinely production-grade ML for atmospheric science! 🌡️⚡")

# SINGLE UID TRACKING

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from datetime import datetime
import warnings
warnings.filterwarnings('ignore')

# Safe cartopy import
try:
    import cartopy.crs as ccrs
    import cartopy.feature as cfeature
    CARTOPY_AVAILABLE = True
    print("✅ Cartopy available")
except ImportError:
    CARTOPY_AVAILABLE = False
    print("⚠️ Cartopy not available - using matplotlib only")

def safe_select_target_uid(tracking_table):
    """Safely select target UID with your specific data structure"""
    print("🎯 SELECTING TARGET SYSTEM")
    print("="*40)

    # Basic validation
    if not isinstance(tracking_table, pd.DataFrame):
        print("❌ Input is not a pandas DataFrame")
        return None, None, None

    if 'uid' not in tracking_table.columns:
        print("❌ No 'uid' column found")
        return None, None, None

    print(f"📊 Data shape: {tracking_table.shape}")
    print(f"📋 Available columns: {list(tracking_table.columns)}")

    # Get UID statistics safely
    try:
        # Convert uid to string to avoid numpy array issues
        tracking_table['uid'] = tracking_table['uid'].astype(str)
        uid_counts = tracking_table['uid'].value_counts()

        print(f"🔢 Found {len(uid_counts)} unique UIDs")
        print(f"🏆 Top 5 longest-lived systems:")
        for i, (uid, count) in enumerate(uid_counts.head(5).items()):
            print(f"   {i+1}. UID {uid}: {count} time steps")

        # Select longest-lived system
        target_uid = uid_counts.index[0]
        target_data = tracking_table[tracking_table['uid'] == target_uid].copy()

        print(f"🌀 Selected UID {target_uid} ({len(target_data)} time steps)")

    except Exception as e:
        print(f"❌ Error selecting UID: {e}")
        return None, None, None

    # Identify coordinate columns for your specific data
    coord_info = None

    # Based on your data structure, u_ and v_ are likely coordinates
    if 'u_' in target_data.columns and 'v_' in target_data.columns:
        # Check if these have reasonable coordinate-like values
        u_vals = pd.to_numeric(target_data['u_'], errors='coerce').dropna()
        v_vals = pd.to_numeric(target_data['v_'], errors='coerce').dropna()

        if len(u_vals) > 0 and len(v_vals) > 0:
            # These might be velocity components, but let's check if they could be coordinates
            u_range = u_vals.max() - u_vals.min()
            v_range = v_vals.max() - v_vals.min()

            print(f"📍 Found u_ column: range {u_vals.min():.3f} to {u_vals.max():.3f} (span: {u_range:.3f})")
            print(f"📍 Found v_ column: range {v_vals.min():.3f} to {v_vals.max():.3f} (span: {v_range:.3f})")

            # If the ranges are small, these might be relative coordinates or velocity
            # Let's use them anyway for trajectory plotting
            coord_info = {'lat_col': 'v_', 'lon_col': 'u_'}
            print(f"✅ Using u_ as longitude, v_ as latitude (relative coordinates)")

    # Alternative: look for any other potential coordinate columns
    if coord_info is None:
        potential_lat_cols = []
        potential_lon_cols = []

        for col in target_data.columns:
            if col in ['uid', 'timestamp', 'file']:
                continue

            try:
                values = pd.to_numeric(target_data[col], errors='coerce').dropna()
                if len(values) > 1:
                    val_min, val_max = values.min(), values.max()
                    val_range = val_max - val_min

                    # Look for columns with reasonable variation
                    if val_range > 0.01:  # Some variation
                        if col.lower().startswith('lat') or 'lat' in col.lower():
                            potential_lat_cols.append((col, val_min, val_max, val_range))
                        elif col.lower().startswith('lon') or 'lon' in col.lower():
                            potential_lon_cols.append((col, val_min, val_max, val_range))
                        elif -90 <= val_min and val_max <= 90 and val_range > 0.1:
                            potential_lat_cols.append((col, val_min, val_max, val_range))
                        elif -180 <= val_min and val_max <= 180 and val_range > 0.1:
                            potential_lon_cols.append((col, val_min, val_max, val_range))
            except:
                continue

        if potential_lat_cols and potential_lon_cols:
            lat_col = potential_lat_cols[0][0]
            lon_col = potential_lon_cols[0][0]
            coord_info = {'lat_col': lat_col, 'lon_col': lon_col}
            print(f"✅ Alternative coordinates: {lat_col} (lat), {lon_col} (lon)")

    if coord_info is None:
        print("⚠️ No suitable coordinate columns found - will create time series only")

    return target_uid, target_data, coord_info

def create_safe_visualization(target_uid, target_data, coord_info):
    """Create visualization with proper error handling"""
    print(f"\n🎨 CREATING VISUALIZATION FOR UID {target_uid}")
    print("="*50)

    if target_data is None or len(target_data) == 0:
        print("❌ No data to visualize")
        return None

    # Determine layout based on available data
    has_coords = coord_info is not None and CARTOPY_AVAILABLE

    if has_coords:
        # Layout with map
        fig = plt.figure(figsize=(18, 12))
        ax_map = plt.subplot(2, 3, (1, 4), projection=ccrs.PlateCarree())
        ax_temp = plt.subplot(2, 3, 2)
        ax_size = plt.subplot(2, 3, 3)
        ax_range = plt.subplot(2, 3, 5)
        ax_stats = plt.subplot(2, 3, 6)

        create_trajectory_plot(ax_map, target_uid, target_data, coord_info)
    else:
        # Time series only layout
        fig, ((ax_temp, ax_size), (ax_range, ax_stats)) = plt.subplots(2, 2, figsize=(15, 10))
        ax_map = None

    # Create time series plots
    create_time_series_analysis(target_uid, target_data, ax_temp, ax_size, ax_range, ax_stats)

    plt.tight_layout()
    plt.show()

    # Print analysis
    print_system_analysis(target_uid, target_data, coord_info)

    return fig

def create_trajectory_plot(ax_map, target_uid, target_data, coord_info):
    """Create trajectory plot with error handling"""
    try:
        lat_col = coord_info['lat_col']
        lon_col = coord_info['lon_col']

        # Safely extract coordinates
        lons = pd.to_numeric(target_data[lon_col], errors='coerce').dropna()
        lats = pd.to_numeric(target_data[lat_col], errors='coerce').dropna()

        if len(lons) == 0 or len(lats) == 0:
            ax_map.text(0.5, 0.5, 'No valid coordinate data',
                       transform=ax_map.transAxes, ha='center', va='center', fontsize=14)
            return

        print(f"📍 Plotting {len(lons)} coordinate points")

        # Calculate extent with margin
        lon_margin = max((lons.max() - lons.min()) * 0.2, 0.1)
        lat_margin = max((lats.max() - lats.min()) * 0.2, 0.1)

        ax_map.set_extent([lons.min() - lon_margin, lons.max() + lon_margin,
                          lats.min() - lat_margin, lats.max() + lat_margin],
                         ccrs.PlateCarree())

        # Add map features
        try:
            ax_map.add_feature(cfeature.COASTLINE, linewidth=1.0, color='darkblue')
            ax_map.add_feature(cfeature.BORDERS, linewidth=0.8, color='black')
            ax_map.add_feature(cfeature.OCEAN, color='lightblue', alpha=0.3)
            ax_map.add_feature(cfeature.LAND, color='lightgray', alpha=0.3)
        except:
            print("⚠️ Some map features unavailable")

        # Plot trajectory
        if len(lons) > 1:
            ax_map.plot(lons, lats, 'k--', linewidth=2, alpha=0.8,
                       transform=ccrs.PlateCarree(), label='System Path')

        # Plot points with color gradient
        colors = np.arange(len(lons))
        scatter = ax_map.scatter(lons, lats, c=colors, s=80, cmap='plasma',
                               alpha=0.8, edgecolors='black', linewidth=0.5,
                               transform=ccrs.PlateCarree(), zorder=5)

        # Start and end markers
        ax_map.plot(lons.iloc[0], lats.iloc[0], 'g^', markersize=12,
                   label='Start', transform=ccrs.PlateCarree(), zorder=6)
        ax_map.plot(lons.iloc[-1], lats.iloc[-1], 'rs', markersize=12,
                   label='End', transform=ccrs.PlateCarree(), zorder=6)

        # Add colorbar safely
        try:
            cbar = plt.colorbar(scatter, ax=ax_map, shrink=0.6, pad=0.05)
            cbar.set_label('Time Step', rotation=270, labelpad=15)
        except:
            print("⚠️ Colorbar creation failed")

        # Add gridlines safely
        try:
            gl = ax_map.gridlines(draw_labels=True, linewidth=0.5, color='gray', alpha=0.7)
            gl.top_labels = False
            gl.right_labels = False
        except:
            print("⚠️ Gridlines creation failed")

        ax_map.set_title(f'System UID {target_uid} - Trajectory', fontsize=12, fontweight='bold')
        ax_map.legend(loc='upper right', fontsize=9)

    except Exception as e:
        print(f"⚠️ Error creating trajectory plot: {e}")
        ax_map.text(0.5, 0.5, f'Trajectory plot error:\n{str(e)}',
                   transform=ax_map.transAxes, ha='center', va='center', fontsize=10)

def create_time_series_analysis(target_uid, target_data, ax_temp, ax_size, ax_range, ax_stats):
    """Create time series plots with your data"""
    time_indices = range(len(target_data))

    # Temperature evolution (mean column)
    if 'mean' in target_data.columns:
        try:
            temps = pd.to_numeric(target_data['mean'], errors='coerce').dropna()
            if len(temps) > 0:
                ax_temp.plot(range(len(temps)), temps, 'b-o', linewidth=2, markersize=4)
                ax_temp.set_title(f'Mean Temperature - UID {target_uid}')
                ax_temp.set_xlabel('Time Step')
                ax_temp.set_ylabel('Temperature (K)')
                ax_temp.grid(True, alpha=0.3)

                # Add trend line
                if len(temps) > 2:
                    z = np.polyfit(range(len(temps)), temps, 1)
                    p = np.poly1d(z)
                    ax_temp.plot(range(len(temps)), p(range(len(temps))), "r--", alpha=0.7,
                                label=f'Trend: {z[0]:.3f} K/step')
                    ax_temp.legend()
        except Exception as e:
            ax_temp.text(0.5, 0.5, f'Temperature plot error:\n{str(e)}',
                        transform=ax_temp.transAxes, ha='center', va='center')

    # Size evolution
    if 'size' in target_data.columns:
        try:
            sizes = pd.to_numeric(target_data['size'], errors='coerce').dropna()
            if len(sizes) > 0:
                ax_size.plot(range(len(sizes)), sizes, 'g-s', linewidth=2, markersize=4)
                ax_size.set_title(f'System Size - UID {target_uid}')
                ax_size.set_xlabel('Time Step')
                ax_size.set_ylabel('Size (pixels)')
                ax_size.grid(True, alpha=0.3)

                # Add trend line
                if len(sizes) > 2:
                    z = np.polyfit(range(len(sizes)), sizes, 1)
                    p = np.poly1d(z)
                    ax_size.plot(range(len(sizes)), p(range(len(sizes))), "r--", alpha=0.7,
                                label=f'Trend: {z[0]:.1f} px/step')
                    ax_size.legend()
        except Exception as e:
            ax_size.text(0.5, 0.5, f'Size plot error:\n{str(e)}',
                        transform=ax_size.transAxes, ha='center', va='center')

    # Temperature range (min/max)
    if 'min' in target_data.columns and 'max' in target_data.columns:
        try:
            min_temps = pd.to_numeric(target_data['min'], errors='coerce').dropna()
            max_temps = pd.to_numeric(target_data['max'], errors='coerce').dropna()

            if len(min_temps) > 0 and len(max_temps) > 0:
                min_len = min(len(min_temps), len(max_temps))
                time_range = range(min_len)

                ax_range.plot(time_range, min_temps[:min_len], 'c-', label='Min Temp', linewidth=2)
                ax_range.plot(time_range, max_temps[:min_len], 'r-', label='Max Temp', linewidth=2)
                ax_range.fill_between(time_range, min_temps[:min_len], max_temps[:min_len],
                                    alpha=0.3, color='yellow')
                ax_range.set_title('Temperature Range')
                ax_range.set_xlabel('Time Step')
                ax_range.set_ylabel('Temperature (K)')
                ax_range.legend()
                ax_range.grid(True, alpha=0.3)
        except Exception as e:
            ax_range.text(0.5, 0.5, f'Range plot error:\n{str(e)}',
                         transform=ax_range.transAxes, ha='center', va='center')

    # Statistics summary
    ax_stats.axis('off')

    try:
        # Create summary
        summary_lines = [
            f"SYSTEM UID {target_uid}",
            "=" * 20,
            f"Duration: {len(target_data)} steps",
            ""
        ]

        if 'timestamp' in target_data.columns:
            timestamps = target_data['timestamp'].values
            summary_lines.extend([
                f"Time Range:",
                f"  Start: {timestamps[0]}",
                f"  End: {timestamps[-1]}",
                ""
            ])

        # Add temperature stats
        if 'mean' in target_data.columns:
            temps = pd.to_numeric(target_data['mean'], errors='coerce').dropna()
            if len(temps) > 0:
                summary_lines.extend([
                    f"Temperature (K):",
                    f"  Min: {temps.min():.1f}",
                    f"  Max: {temps.max():.1f}",
                    f"  Avg: {temps.mean():.1f}",
                    f"  Change: {temps.iloc[-1] - temps.iloc[0]:+.1f}",
                    ""
                ])

        # Add size stats
        if 'size' in target_data.columns:
            sizes = pd.to_numeric(target_data['size'], errors='coerce').dropna()
            if len(sizes) > 0:
                summary_lines.extend([
                    f"Size (pixels):",
                    f"  Min: {sizes.min():.0f}",
                    f"  Max: {sizes.max():.0f}",
                    f"  Avg: {sizes.mean():.0f}",
                    f"  Change: {sizes.iloc[-1] - sizes.iloc[0]:+.0f}",
                ])

        summary_text = '\n'.join(summary_lines)

        ax_stats.text(0.05, 0.95, summary_text, transform=ax_stats.transAxes,
                      fontsize=10, verticalalignment='top', fontfamily='monospace',
                      bbox=dict(boxstyle='round', facecolor='lightcyan', alpha=0.8))

    except Exception as e:
        ax_stats.text(0.5, 0.5, f'Stats error:\n{str(e)}',
                     transform=ax_stats.transAxes, ha='center', va='center')

def print_system_analysis(target_uid, target_data, coord_info):
    """Print comprehensive analysis"""
    print(f"\n🌀 SYSTEM ANALYSIS - UID {target_uid}")
    print("="*60)

    try:
        print(f"📊 Basic Information:")
        print(f"   Duration: {len(target_data)} time steps")

        if 'timestamp' in target_data.columns:
            timestamps = target_data['timestamp'].values
            print(f"   Time span: {timestamps[0]} → {timestamps[-1]}")

        # Temperature analysis
        if 'mean' in target_data.columns:
            temps = pd.to_numeric(target_data['mean'], errors='coerce').dropna()
            if len(temps) > 0:
                print(f"\n🌡️ Temperature Analysis:")
                print(f"   Range: {temps.min():.1f} - {temps.max():.1f} K")
                print(f"   Average: {temps.mean():.1f} ± {temps.std():.1f} K")
                print(f"   Total change: {temps.iloc[-1] - temps.iloc[0]:+.1f} K")

                # Classify behavior
                if temps.iloc[-1] < temps.iloc[0] - 5:
                    print(f"   🥶 System is COOLING (intensifying)")
                elif temps.iloc[-1] > temps.iloc[0] + 5:
                    print(f"   🌡️ System is WARMING (weakening)")
                else:
                    print(f"   ⚖️ System temperature is STABLE")

        # Size analysis
        if 'size' in target_data.columns:
            sizes = pd.to_numeric(target_data['size'], errors='coerce').dropna()
            if len(sizes) > 0:
                print(f"\n📏 Size Analysis:")
                print(f"   Range: {sizes.min():.0f} - {sizes.max():.0f} pixels")
                print(f"   Average: {sizes.mean():.0f} ± {sizes.std():.0f} pixels")
                print(f"   Growth: {sizes.iloc[-1] - sizes.iloc[0]:+.0f} pixels")

                # Classify behavior
                if sizes.iloc[-1] > sizes.iloc[0] * 1.2:
                    print(f"   📈 System is GROWING")
                elif sizes.iloc[-1] < sizes.iloc[0] * 0.8:
                    print(f"   📉 System is SHRINKING")
                else:
                    print(f"   📊 System size is STABLE")

        # Coordinate analysis
        if coord_info:
            lat_col = coord_info['lat_col']
            lon_col = coord_info['lon_col']

            lats = pd.to_numeric(target_data[lat_col], errors='coerce').dropna()
            lons = pd.to_numeric(target_data[lon_col], errors='coerce').dropna()

            if len(lats) > 0 and len(lons) > 0:
                print(f"\n🗺️ Movement Analysis:")
                print(f"   Start position: ({lats.iloc[0]:.3f}, {lons.iloc[0]:.3f})")
                print(f"   End position: ({lats.iloc[-1]:.3f}, {lons.iloc[-1]:.3f})")

                # Calculate total movement
                if len(lats) > 1 and len(lons) > 1:
                    total_movement = 0
                    for i in range(1, min(len(lats), len(lons))):
                        dx = abs(lons.iloc[i] - lons.iloc[i-1])
                        dy = abs(lats.iloc[i] - lats.iloc[i-1])
                        movement = np.sqrt(dx**2 + dy**2)
                        total_movement += movement
                    print(f"   Total movement: {total_movement:.3f} coordinate units")

                    if total_movement > 0.1:
                        print(f"   🚀 System is MOBILE")
                    else:
                        print(f"   🏠 System is relatively STATIONARY")

    except Exception as e:
        print(f"⚠️ Error in analysis: {e}")

def create_simple_animation_frames(target_uid, target_data, coord_info):
    """Create simple animation frames"""
    if not coord_info:
        print("❌ Cannot create animation without coordinates")
        return False

    try:
        print(f"\n🎬 Creating animation frames for UID {target_uid}...")

        lat_col = coord_info['lat_col']
        lon_col = coord_info['lon_col']

        lats = pd.to_numeric(target_data[lat_col], errors='coerce').dropna()
        lons = pd.to_numeric(target_data[lon_col], errors='coerce').dropna()

        if len(lats) < 2 or len(lons) < 2:
            print("❌ Not enough coordinate data for animation")
            return False

        # Create animation frames
        n_frames = min(8, len(lats))
        frame_indices = np.linspace(0, len(lats)-1, n_frames, dtype=int)

        fig, axes = plt.subplots(2, 4, figsize=(16, 8))
        axes = axes.flatten()

        for i, frame_idx in enumerate(frame_indices):
            ax = axes[i]

            # Plot full trajectory (faded)
            ax.plot(lons, lats, 'lightgray', linewidth=1, alpha=0.4, label='Full path')

            # Plot current trajectory (up to this frame)
            current_lons = lons[:frame_idx+1]
            current_lats = lats[:frame_idx+1]
            ax.plot(current_lons, current_lats, 'blue', linewidth=2, label='Current path')

            # Current position
            ax.plot(lons.iloc[frame_idx], lats.iloc[frame_idx], 'ro', markersize=8, label='Current pos')

            # Set consistent extent
            margin = max((lons.max() - lons.min()) * 0.1, (lats.max() - lats.min()) * 0.1, 0.01)
            ax.set_xlim(lons.min() - margin, lons.max() + margin)
            ax.set_ylim(lats.min() - margin, lats.max() + margin)

            ax.set_title(f'Step {frame_idx+1}/{len(lats)}')
            ax.grid(True, alpha=0.3)

            if i == 0:
                ax.legend(fontsize=8)

        plt.tight_layout()
        plt.suptitle(f'System UID {target_uid} - Movement Animation', y=1.02)
        plt.show()

        print("✅ Animation frames created!")
        return True

    except Exception as e:
        print(f"❌ Animation failed: {e}")
        return False

# MAIN EXECUTION
print("🚀 FINAL FIXED VERSION - Handling Your Specific Data")
print("="*70)

# Check for tracking results
if 'tracking_results' not in globals() or tracking_results is None:
    print("❌ No 'tracking_results' variable found!")

    # Look for any DataFrame with uid column
    found_data = False
    for var_name in globals():
        var_value = globals()[var_name]
        if (isinstance(var_value, pd.DataFrame) and
            hasattr(var_value, 'columns') and
            'uid' in var_value.columns):
            print(f"✅ Found potential tracking data: '{var_name}'")
            tracking_results = var_value
            found_data = True
            break

    if not found_data:
        print("❌ No suitable DataFrame found")
        print("Available variables:", [v for v in globals().keys() if not v.startswith('_')])

if 'tracking_results' in globals() and tracking_results is not None:
    try:
        print(f"📊 Processing data: {tracking_results.shape}")

        # Step 1: Select target UID
        target_uid, target_data, coord_info = safe_select_target_uid(tracking_results)

        if target_uid is not None and target_data is not None:
            # Step 2: Create visualization
            fig = create_safe_visualization(target_uid, target_data, coord_info)

            # Step 3: Try animation frames
            animation_success = False
            if coord_info:
                animation_success = create_simple_animation_frames(target_uid, target_data, coord_info)

            # Final summary
            print(f"\n🎉 TRACKING ANALYSIS COMPLETE!")
            print(f"="*50)
            print(f"✅ Target UID: {target_uid}")
            print(f"✅ Data points: {len(target_data)}")
            print(f"✅ Visualization: Created")
            print(f"{'✅' if animation_success else '⚠️'} Animation: {'Created' if animation_success else 'Skipped'}")
            print(f"✅ Analysis: Complete")

        else:
            print("❌ Failed to process tracking data")

    except Exception as e:
        print(f"❌ Execution error: {e}")
        import traceback
        traceback.print_exc()

        # Show basic info about the data
        if hasattr(tracking_results, 'info'):
            print("\n📋 Data info:")
            tracking_results.info()

print(f"\n💡 This version specifically handles:")
print(f"   • Your exact column structure (u_, v_, mean, size, etc.)")
print(f"   • Numpy array issues with proper type conversion")
print(f"   • Safe error handling at every step")
print(f"   • Fallback visualizations when map features fail")
print(f"   • Manual animation frames instead of external dependencies")

# SINGLE UID TRACKING-PyFORTRACC Integration Validation and Enhancement
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

def validate_pyfortracc_tracking(tracking_data):
    """
    Validate if the tracking data follows PyFORTRACC methodology
    """
    print("🔍 PYFORTRACC TRACKING VALIDATION")
    print("="*50)

    # Check for PyFORTRACC-specific columns
    expected_cols = {
        'uid': 'Unique system identifier',
        'timestamp': 'Time information',
        'size': 'System area/size',
        'mean': 'Mean temperature/intensity',
        'min': 'Minimum value',
        'max': 'Maximum value'
    }

    missing_cols = []
    present_cols = []

    for col, desc in expected_cols.items():
        if col in tracking_data.columns:
            present_cols.append(f"✅ {col}: {desc}")
        else:
            missing_cols.append(f"❌ {col}: {desc}")

    print("Required PyFORTRACC columns:")
    for col in present_cols:
        print(f"  {col}")

    if missing_cols:
        print("\nMissing columns:")
        for col in missing_cols:
            print(f"  {col}")

    # Validate tracking continuity
    print(f"\n📊 Tracking Statistics:")
    uid_counts = tracking_data['uid'].value_counts()
    print(f"  Total systems tracked: {len(uid_counts)}")
    print(f"  Longest track: {uid_counts.max()} time steps")
    print(f"  Shortest track: {uid_counts.min()} time steps")
    print(f"  Average track length: {uid_counts.mean():.1f} time steps")

    # Check for temporal continuity
    if 'timestamp' in tracking_data.columns:
        print(f"\n⏰ Temporal Analysis:")
        timestamps = pd.to_datetime(tracking_data['timestamp'], errors='coerce')
        if not timestamps.isna().all():
            time_span = timestamps.max() - timestamps.min()
            print(f"  Time span: {time_span}")

            # Check time intervals
            unique_times = timestamps.dropna().unique()
            if len(unique_times) > 1:
                time_diffs = np.diff(np.sort(unique_times))
                avg_interval = np.median(time_diffs)
                print(f"  Typical time interval: {avg_interval}")

    return present_cols, missing_cols

def enhance_pyfortracc_tracking(tracking_data, target_uid):
    """
    Enhance tracking analysis with PyFORTRACC-specific metrics
    """
    print(f"\n🌀 ENHANCED PYFORTRACC ANALYSIS - UID {target_uid}")
    print("="*60)

    target_data = tracking_data[tracking_data['uid'] == target_uid].copy()

    if len(target_data) == 0:
        print(f"❌ No data found for UID {target_uid}")
        return None

    # Sort by timestamp if available
    if 'timestamp' in target_data.columns:
        target_data = target_data.sort_values('timestamp')

    print(f"📈 System Evolution Analysis:")

    # 1. Lifecycle stages
    if 'size' in target_data.columns:
        sizes = pd.to_numeric(target_data['size'], errors='coerce').dropna()
        if len(sizes) > 0:
            # Detect lifecycle phases
            max_size_idx = sizes.idxmax()
            max_size_pos = list(sizes.index).index(max_size_idx)

            genesis_phase = max_size_pos / len(sizes) if len(sizes) > 0 else 0

            print(f"  🌱 Genesis phase: {genesis_phase:.1%} of lifecycle")
            print(f"  🌪️ Maximum size: {sizes.max():.0f} at step {max_size_pos}")
            print(f"  📊 Size variability: {sizes.std()/sizes.mean():.2f} (CV)")

    # 2. Intensity evolution
    if 'mean' in target_data.columns:
        temps = pd.to_numeric(target_data['mean'], errors='coerce').dropna()
        if len(temps) > 0:
            # Temperature trend analysis
            temp_trend = np.polyfit(range(len(temps)), temps, 1)[0]
            temp_variability = temps.std()

            print(f"  🌡️ Temperature trend: {temp_trend:.3f} K/step")
            print(f"  🌡️ Temperature variability: ±{temp_variability:.1f} K")

            # Classify system behavior
            if temp_trend < -0.1:
                behavior = "INTENSIFYING (cooling)"
            elif temp_trend > 0.1:
                behavior = "WEAKENING (warming)"
            else:
                behavior = "STABLE"
            print(f"  🎯 System behavior: {behavior}")

    # 3. Movement characteristics
    if 'u_' in target_data.columns and 'v_' in target_data.columns:
        u_vals = pd.to_numeric(target_data['u_'], errors='coerce').dropna()
        v_vals = pd.to_numeric(target_data['v_'], errors='coerce').dropna()

        if len(u_vals) > 1 and len(v_vals) > 1:
            # Calculate movement metrics
            total_displacement = np.sqrt((u_vals.iloc[-1] - u_vals.iloc[0])**2 +
                                       (v_vals.iloc[-1] - v_vals.iloc[0])**2)

            # Calculate path length
            path_length = 0
            for i in range(1, min(len(u_vals), len(v_vals))):
                dx = u_vals.iloc[i] - u_vals.iloc[i-1]
                dy = v_vals.iloc[i] - v_vals.iloc[i-1]
                path_length += np.sqrt(dx**2 + dy**2)

            if path_length > 0:
                path_efficiency = total_displacement / path_length
                print(f"  🚀 Total displacement: {total_displacement:.3f} units")
                print(f"  📏 Path length: {path_length:.3f} units")
                print(f"  🎯 Path efficiency: {path_efficiency:.2f}")

                # Movement classification
                if path_efficiency > 0.7:
                    movement_type = "DIRECT (straight path)"
                elif path_efficiency > 0.3:
                    movement_type = "MEANDERING"
                else:
                    movement_type = "HIGHLY CURVED"
                print(f"  🌪️ Movement pattern: {movement_type}")

    return target_data

def create_pyfortracc_diagnostic_plots(target_data, target_uid):
    """
    Create diagnostic plots specific to PyFORTRACC tracking
    """
    fig, axes = plt.subplots(2, 3, figsize=(18, 12))

    # 1. Size evolution with lifecycle phases
    if 'size' in target_data.columns:
        sizes = pd.to_numeric(target_data['size'], errors='coerce').dropna()
        time_steps = range(len(sizes))

        axes[0,0].semilogy(time_steps, sizes, 'b-o', linewidth=2, markersize=4)
        axes[0,0].set_title('System Size Evolution (Log Scale)')
        axes[0,0].set_xlabel('Time Step')
        axes[0,0].set_ylabel('Size (pixels)')
        axes[0,0].grid(True, alpha=0.3)

        # Mark lifecycle phases
        if len(sizes) > 0:
            max_idx = sizes.idxmax()
            max_pos = list(sizes.index).index(max_idx)
            axes[0,0].axvline(max_pos, color='red', linestyle='--', alpha=0.7, label='Peak size')
            axes[0,0].legend()

    # 2. Temperature evolution with trends
    if 'mean' in target_data.columns:
        temps = pd.to_numeric(target_data['mean'], errors='coerce').dropna()
        time_steps = range(len(temps))

        axes[0,1].plot(time_steps, temps, 'r-o', linewidth=2, markersize=3)

        # Add moving average
        if len(temps) > 5:
            window = min(len(temps)//5, 10)
            moving_avg = temps.rolling(window=window, center=True).mean()
            axes[0,1].plot(time_steps, moving_avg, 'k--', linewidth=2, label=f'{window}-step average')
            axes[0,1].legend()

        axes[0,1].set_title('Temperature Evolution')
        axes[0,1].set_xlabel('Time Step')
        axes[0,1].set_ylabel('Temperature (K)')
        axes[0,1].grid(True, alpha=0.3)

    # 3. Movement vector field
    if 'u_' in target_data.columns and 'v_' in target_data.columns:
        u_vals = pd.to_numeric(target_data['u_'], errors='coerce').dropna()
        v_vals = pd.to_numeric(target_data['v_'], errors='coerce').dropna()

        if len(u_vals) > 1 and len(v_vals) > 1:
            # Calculate velocity vectors
            du = np.diff(u_vals)
            dv = np.diff(v_vals)

            # Plot trajectory with velocity vectors
            axes[0,2].plot(u_vals, v_vals, 'b-', linewidth=2, alpha=0.7)
            axes[0,2].scatter(u_vals, v_vals, c=range(len(u_vals)), cmap='plasma', s=50, zorder=5)

            # Add velocity vectors at selected points
            n_vectors = min(10, len(du))
            indices = np.linspace(0, len(du)-1, n_vectors, dtype=int)

            for i in indices:
                axes[0,2].arrow(u_vals.iloc[i], v_vals.iloc[i], du[i]*10, dv[i]*10,
                               head_width=0.02, head_length=0.02, fc='red', ec='red', alpha=0.7)

            axes[0,2].set_title('Trajectory with Movement Vectors')
            axes[0,2].set_xlabel('U coordinate')
            axes[0,2].set_ylabel('V coordinate')
            axes[0,2].grid(True, alpha=0.3)
            axes[0,2].axis('equal')

    # 4. Intensity distribution
    if 'mean' in target_data.columns:
        temps = pd.to_numeric(target_data['mean'], errors='coerce').dropna()
        axes[1,0].hist(temps, bins=20, alpha=0.7, color='skyblue', edgecolor='black')
        axes[1,0].axvline(temps.mean(), color='red', linestyle='--', label=f'Mean: {temps.mean():.1f} K')
        axes[1,0].set_title('Temperature Distribution')
        axes[1,0].set_xlabel('Temperature (K)')
        axes[1,0].set_ylabel('Frequency')
        axes[1,0].legend()
        axes[1,0].grid(True, alpha=0.3)

    # 5. Size vs Temperature relationship
    if 'size' in target_data.columns and 'mean' in target_data.columns:
        sizes = pd.to_numeric(target_data['size'], errors='coerce').dropna()
        temps = pd.to_numeric(target_data['mean'], errors='coerce').dropna()

        if len(sizes) > 0 and len(temps) > 0:
            # Align lengths
            min_len = min(len(sizes), len(temps))
            sizes_aligned = sizes.iloc[:min_len]
            temps_aligned = temps.iloc[:min_len]

            scatter = axes[1,1].scatter(temps_aligned, sizes_aligned,
                                     c=range(min_len), cmap='viridis',
                                     alpha=0.7, s=50)
            axes[1,1].set_title('Size vs Temperature Evolution')
            axes[1,1].set_xlabel('Temperature (K)')
            axes[1,1].set_ylabel('Size (pixels)')
            axes[1,1].grid(True, alpha=0.3)

            # Add colorbar for time
            cbar = plt.colorbar(scatter, ax=axes[1,1])
            cbar.set_label('Time Step')

    # 6. System summary statistics
    axes[1,2].axis('off')

    # Create summary text
    summary_text = f"PyFORTRACC System Summary\n"
    summary_text += f"{'='*25}\n"
    summary_text += f"UID: {target_uid}\n"
    summary_text += f"Duration: {len(target_data)} steps\n\n"

    if 'size' in target_data.columns:
        sizes = pd.to_numeric(target_data['size'], errors='coerce').dropna()
        if len(sizes) > 0:
            summary_text += f"Size Statistics:\n"
            summary_text += f"  Initial: {sizes.iloc[0]:,.0f} px\n"
            summary_text += f"  Maximum: {sizes.max():,.0f} px\n"
            summary_text += f"  Final: {sizes.iloc[-1]:,.0f} px\n"
            summary_text += f"  Growth: {((sizes.iloc[-1]/sizes.iloc[0])-1)*100:+.1f}%\n\n"

    if 'mean' in target_data.columns:
        temps = pd.to_numeric(target_data['mean'], errors='coerce').dropna()
        if len(temps) > 0:
            summary_text += f"Temperature Statistics:\n"
            summary_text += f"  Initial: {temps.iloc[0]:.1f} K\n"
            summary_text += f"  Minimum: {temps.min():.1f} K\n"
            summary_text += f"  Final: {temps.iloc[-1]:.1f} K\n"
            summary_text += f"  Change: {temps.iloc[-1] - temps.iloc[0]:+.1f} K\n"

    axes[1,2].text(0.05, 0.95, summary_text, transform=axes[1,2].transAxes,
                   fontsize=11, verticalalignment='top', fontfamily='monospace',
                   bbox=dict(boxstyle='round', facecolor='lightcyan', alpha=0.8))

    plt.suptitle(f'PyFORTRACC Tracking Analysis - System UID {target_uid}',
                 fontsize=16, fontweight='bold')
    plt.tight_layout()
    plt.show()

    return fig

# Usage example (assuming tracking_results exists)
if 'tracking_results' in globals():
    # Validate the tracking approach
    present_cols, missing_cols = validate_pyfortracc_tracking(tracking_results)

    # Select longest-lived system
    uid_counts = tracking_results['uid'].value_counts()
    target_uid = uid_counts.index[0]

    # Enhanced analysis
    enhanced_data = enhance_pyfortracc_tracking(tracking_results, target_uid)

    if enhanced_data is not None:
        # Create diagnostic plots
        fig = create_pyfortracc_diagnostic_plots(enhanced_data, target_uid)

        print(f"\n✅ PyFORTRACC tracking validation complete!")
        print(f"📊 System UID {target_uid} analyzed with {len(enhanced_data)} time steps")
else:
    print("❌ No tracking_results data available for validation")

plot_animation(
    read_function=read_function,
    name_list=name_list,
    start_timestamp=str(tracking_table['timestamp'].min()),
    end_timestamp=str(tracking_table['timestamp'].max()),
    figsize=(8, 6),
    trajectory=True,
    smooth_trajectory=True,
    cmap='turbo',
    min_val=180,  # More aggressive - removes more boundary pixels
    max_val=235,
    nan_value=180,  # Set invalid values to 180K
    nan_operation=np.less,  # Mask values less than 180K
    bound_color='white',  # Change boundary color to white/transparent
    info_cols=['uid'],
    parallel=False
)